import {StyleSheet} from 'react-native';
import type {ColorPalette} from '../../theme/colors';
import {createShadows, fontSize, radius, spacing} from '../../theme';

export const createAIScreenStyles = (colors: ColorPalette) => {
  const shadows = createShadows(colors);
  return StyleSheet.create({
  container: {flex: 1, backgroundColor: colors.background},
  flex: {flex: 1},
  header: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.backgroundSecondary,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginBottom: spacing.sm,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.primaryMuted,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 10, 0.35)',
  },
  headerTitle: {
    fontSize: fontSize.xxl,
    color: colors.text,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    marginTop: 2,
  },
  carBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.sm,
    backgroundColor: colors.card,
    padding: spacing.sm,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  carBannerText: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: '500',
    flex: 1,
  },
  locationBar: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  locationLabel: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    fontWeight: '600',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: spacing.sm,
  },
  locationChips: {flexDirection: 'row', gap: spacing.sm},
  locationChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    borderRadius: radius.pill,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
  },
  locationChipSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    ...shadows.glow,
  },
  locationChipText: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  locationChipTextSelected: {color: colors.onPrimary},
  suggestionsWrap: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
  },
  suggestionsLabel: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    fontWeight: '600',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  suggestionChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radius.pill,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: spacing.sm,
  },
  suggestionText: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xxl,
  },
  emptyTitle: {
    fontSize: fontSize.xl,
    color: colors.text,
    fontWeight: '700',
    marginTop: spacing.md,
    marginBottom: spacing.sm,
  },
  emptySubtitle: {
    fontSize: fontSize.md,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
  },
  messageList: {
    padding: spacing.lg,
    paddingBottom: spacing.sm,
  },
  bubble: {
    borderRadius: radius.lg,
    padding: spacing.md,
    marginBottom: 6,
    maxWidth: '88%',
    borderWidth: 1,
    borderColor: colors.border,
  },
  userBubble: {
    backgroundColor: colors.primary,
    borderColor: 'rgba(255, 214, 10, 0.5)',
    alignSelf: 'flex-end',
    ...shadows.glow,
  },
  aiBubble: {
    backgroundColor: colors.cardElevated,
    alignSelf: 'flex-start',
  },
  roleLabel: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    marginBottom: 4,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  userRoleLabel: {color: 'rgba(11, 11, 11, 0.55)'},
  messageText: {color: colors.text, fontSize: fontSize.md, lineHeight: 22},
  userMessageText: {color: colors.onPrimary, fontWeight: '500'},
  partsSection: {alignSelf: 'stretch', marginBottom: spacing.sm, marginTop: 4},
  partsSectionTitle: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    fontWeight: '600',
    marginBottom: spacing.sm,
    marginLeft: 2,
  },
  partsScroll: {flexDirection: 'row'},
  partCard: {
    backgroundColor: colors.card,
    borderRadius: radius.md,
    overflow: 'hidden',
    marginRight: spacing.sm,
    width: 168,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.soft,
  },
  partImage: {width: '100%', height: 100, backgroundColor: colors.surface},
  partImagePlaceholder: {
    width: '100%',
    height: 100,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  partSource: {
    fontSize: 10,
    color: colors.textMuted,
    marginTop: spacing.sm,
    marginHorizontal: spacing.sm,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  partName: {
    fontSize: fontSize.sm,
    color: colors.text,
    fontWeight: '600',
    marginHorizontal: spacing.sm,
    marginBottom: 4,
    lineHeight: 18,
  },
  partPrice: {
    fontSize: fontSize.md,
    color: colors.primary,
    fontWeight: '700',
    marginHorizontal: spacing.sm,
    marginBottom: spacing.sm,
  },
  partViewBtn: {
    backgroundColor: colors.surfaceLight,
    paddingVertical: 8,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  partViewBtnText: {
    fontSize: fontSize.xs,
    color: colors.primary,
    fontWeight: '700',
  },
  detailOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlay,
  },
  detailPanel: {
    backgroundColor: colors.cardElevated,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
  },
  detailImage: {width: '100%', height: 220, backgroundColor: colors.surface},
  detailImagePlaceholder: {
    width: '100%',
    height: 220,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailBody: {padding: spacing.lg},
  detailSourceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  detailSource: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  detailCondition: {fontSize: fontSize.sm, color: colors.textSecondary},
  detailName: {
    fontSize: fontSize.xl,
    color: colors.text,
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  detailPrice: {
    fontSize: 28,
    color: colors.primary,
    fontWeight: '700',
    marginBottom: spacing.md,
  },
  detailBuyBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: spacing.sm,
    ...shadows.glow,
  },
  detailBuyBtnText: {
    color: colors.onPrimary,
    fontSize: fontSize.md,
    fontWeight: '700',
  },
  detailCloseBtn: {paddingVertical: 12, alignItems: 'center'},
  detailCloseBtnText: {color: colors.textMuted, fontSize: fontSize.md},
  loadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm,
    gap: spacing.sm,
  },
  loadingText: {color: colors.textSecondary, fontSize: fontSize.sm},
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    padding: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.backgroundSecondary,
    gap: spacing.sm,
  },
  input: {
    flex: 1,
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    color: colors.text,
    fontSize: fontSize.md,
    maxHeight: 100,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sendButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.glow,
  },
  sendDisabled: {opacity: 0.45},
  attachBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  attachPreviewRow: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm,
    backgroundColor: colors.backgroundSecondary,
  },
  attachThumbWrap: {
    position: 'relative',
    alignSelf: 'flex-start',
  },
  attachThumb: {
    width: 72,
    height: 72,
    borderRadius: radius.md,
  },
  attachRemoveBtn: {
    position: 'absolute',
    top: -6,
    right: -6,
  },
  msgImage: {
    width: 200,
    height: 140,
    borderRadius: radius.sm,
    marginBottom: spacing.xs,
  },
  });
};
