import {StyleSheet} from 'react-native';
import type {ColorPalette} from '../../theme/colors';
import {fontSize, radius, spacing} from '../../theme';

export const createCustomizationScreenStyles = (colors: ColorPalette) =>
  StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  title: {
    fontSize: fontSize.title,
    color: colors.text,
    fontWeight: '700',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    letterSpacing: -0.3,
  },
  titleSub: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    paddingHorizontal: spacing.lg,
    marginTop: 4,
    marginBottom: spacing.sm,
  },
  carBannerSpacing: {
    marginHorizontal: spacing.lg,
    marginBottom: spacing.md,
  },
  carBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.card,
    marginHorizontal: spacing.lg,
    marginTop: spacing.xs,
    borderRadius: 14,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  carBannerText: {
    color: colors.textSecondary,
    fontWeight: '600',
    fontSize: fontSize.md,
    flex: 1,
  },
  tabBar: {
    flexDirection: 'row',
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    borderRadius: 20,
    backgroundColor: colors.card,
    padding: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  tab: {
    flex: 1,
    alignSelf: 'stretch',
    minHeight: 44,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
  },
  tabActive: {
    backgroundColor: colors.primary,
  },
  tabText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '600',
    textAlign: 'center',
  },
  tabTextActive: {
    color: colors.onPrimary,
    fontWeight: '700',
  },
  content: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  searchRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  searchInput: {
    flex: 1,
    backgroundColor: colors.card,
    borderRadius: 18,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    color: colors.text,
    fontSize: fontSize.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  searchBtn: {
    backgroundColor: colors.primary,
    borderRadius: 18,
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categorySection: {marginTop: spacing.lg},
  categorySectionTitle: {
    fontSize: fontSize.lg,
    color: colors.text,
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  categoryCard: {
    width: '31%',
    flexGrow: 1,
    minWidth: '30%',
    backgroundColor: colors.card,
    borderRadius: 18,
    padding: spacing.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  categoryIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 214, 10, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  categoryLabel: {
    fontSize: fontSize.xs,
    color: colors.text,
    fontWeight: '600',
    textAlign: 'center',
  },
  trendingRow: {marginTop: spacing.lg},
  trendingChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: colors.cardElevated,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: spacing.sm,
  },
  trendingText: {color: colors.textSecondary, fontSize: fontSize.sm},
  sourceLabel: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    marginTop: spacing.sm,
    marginBottom: 2,
  },
  optimizedQueryLabel: {
    color: colors.textSecondary,
    fontSize: 10,
    marginBottom: 4,
    fontStyle: 'italic',
  },
  errorText: {
    color: colors.danger,
    textAlign: 'center',
    marginTop: spacing.md,
  },
  warningText: {
    color: colors.primary,
    textAlign: 'center',
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
    fontSize: 13,
    lineHeight: 18,
  },
  loader: {
    marginTop: spacing.xl,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(255, 214, 10, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  emptyText: {
    color: colors.textSecondary,
    fontSize: fontSize.lg,
  },
  emptyHint: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    marginTop: spacing.sm,
    textAlign: 'center',
    paddingHorizontal: spacing.xl,
  },
  list: {
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
  },
  partsBody: {
    flex: 1,
    minHeight: 0,
  },
  partsList: {
    flex: 1,
  },
  buildFooter: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.background,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  cardImage: {
    width: '100%',
    height: 160,
    backgroundColor: colors.surfaceLight,
  },
  cardImagePlaceholder: {
    width: '100%',
    height: 160,
    backgroundColor: colors.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardImagePlaceholderText: {
    fontSize: 40,
  },
  cardSelected: {
    borderColor: colors.primary,
    borderWidth: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
  },
  partTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '600',
    flex: 1,
  },
  sourceBadge: {
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  sourceBadgeText: {
    color: colors.onAiAssistant,
    fontSize: fontSize.sm,
    fontWeight: '700',
  },
  cardBody: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  price: {
    color: colors.primary,
    fontSize: fontSize.lg,
    fontWeight: 'bold',
  },
  condition: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: 'normal',
  },
  checkmark: {
    color: colors.primary,
    fontSize: fontSize.xxl,
    fontWeight: 'bold',
  },
  linkBtn: {
    marginTop: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.md,
  },
  linkText: {
    color: colors.primary,
    fontSize: fontSize.sm,
    fontWeight: '600',
  },
  shopAddress: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
    marginTop: 4,
  },
  shopRating: {
    color: colors.warning,
    fontSize: fontSize.md,
    marginTop: 4,
  },
  cartTray: {
    backgroundColor: colors.card,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
  },
  cartTrayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    marginBottom: spacing.sm,
  },
  cartTrayTitle: {
    fontSize: fontSize.sm,
    color: colors.text,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  cartTrayTotal: {
    fontSize: fontSize.md,
    color: colors.primary,
    fontWeight: '700',
  },
  cartTrayScroll: {
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
    paddingBottom: spacing.xs,
  },
  cartCard: {
    width: 140,
    backgroundColor: colors.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
  },
  cartCardImage: {
    width: 52,
    height: 52,
    backgroundColor: colors.surfaceLight,
  },
  cartCardImagePlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartCardInfo: {
    flex: 1,
    padding: 6,
  },
  cartCardName: {
    fontSize: 10,
    color: colors.text,
    fontWeight: '600',
    lineHeight: 13,
    marginBottom: 2,
  },
  cartCardPrice: {
    fontSize: fontSize.xs,
    color: colors.primary,
    fontWeight: '700',
  },
  cartCardRemove: {
    padding: 4,
    alignSelf: 'flex-start',
  },
  totalBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
  },
  totalText: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
  },
  totalPrice: {
    color: colors.primary,
    fontSize: fontSize.xl,
    fontWeight: 'bold',
  },
  shopRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  mapsLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: spacing.sm,
  },
  mapsLinkText: {
    color: colors.primary,
    fontSize: fontSize.sm,
    fontWeight: '600',
  },
  refreshShopsBtn: {
    marginTop: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: 12,
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
    alignSelf: 'center',
  },
  refreshShopsText: {
    color: colors.onPrimary,
    fontWeight: '700',
    fontSize: fontSize.md,
  },
  shopsTab: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  shopsTabHeader: {
    width: '100%',
    marginBottom: spacing.sm,
  },
  shopsTabSubtitle: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    textAlign: 'center',
    marginTop: spacing.xs,
    paddingHorizontal: spacing.lg,
  },
  shopsCentered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
  },
  shopsLoadingText: {
    color: colors.textSecondary,
    marginTop: spacing.md,
    fontSize: fontSize.md,
  },
  shopsEmptyTitle: {
    textAlign: 'center',
  },
  shopsScroll: {
    flex: 1,
  },
  shopsList: {
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl,
    alignItems: 'center',
    flexGrow: 1,
  },
  shopCardWrap: {
    width: '100%',
    maxWidth: 400,
    marginBottom: spacing.md,
    alignSelf: 'center',
  },
  shopCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    width: '100%',
  },
  shopCardImage: {
    width: '100%',
    height: 180,
    backgroundColor: colors.surfaceLight,
  },
  shopCardImagePlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  shopCardBody: {
    padding: spacing.md,
    alignItems: 'stretch',
    width: '100%',
  },
  shopStatusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: radius.pill,
    marginBottom: spacing.sm,
    alignSelf: 'center',
  },
  shopStatusText: {
    color: colors.onPrimary,
    fontSize: fontSize.xs,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  shopCardTitle: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: spacing.sm,
    lineHeight: 24,
    alignSelf: 'center',
  },
  shopInfoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    marginBottom: spacing.sm,
    width: '100%',
  },
  shopInfoText: {
    flex: 1,
    flexShrink: 1,
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    lineHeight: 20,
  },
  shopInfoLink: {
    color: colors.primary,
    textDecorationLine: 'underline',
  },
  shopMapsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.pill,
    marginTop: spacing.sm,
    width: '100%',
  },
  shopMapsBtnText: {
    color: colors.onPrimary,
    fontSize: fontSize.md,
    fontWeight: '700',
  },
  previewContent: {
    paddingBottom: 120,
    flexGrow: 1,
  },
  previewHeading: {
    color: colors.text,
    fontSize: fontSize.xl,
    fontWeight: 'bold',
    marginBottom: spacing.sm,
  },
  previewSubtext: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
    marginBottom: spacing.md,
  },
  previewCart: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: spacing.md,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  previewCartRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  previewCartIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: 'rgba(255,214,10,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewCartMeta: {
    flex: 1,
  },
  previewCartTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '700',
  },
  previewCartPrice: {
    color: colors.accent,
    fontSize: fontSize.sm,
    fontWeight: '600',
    marginTop: 2,
  },
  previewCartHint: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    marginTop: spacing.sm,
    fontStyle: 'italic',
  },

  buildPanel: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: '75%',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  buildModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  buildModalTitle: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '700',
  },
  buildModalList: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  buildModalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  buildModalThumb: {
    width: 64,
    height: 64,
    borderRadius: 8,
    backgroundColor: colors.surfaceLight,
  },
  buildModalThumbPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  buildModalInfo: {
    flex: 1,
    gap: 6,
  },
  buildModalItemName: {
    color: colors.text,
    fontSize: fontSize.sm,
    fontWeight: '600',
    lineHeight: 18,
  },
  buildModalItemMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  buildModalItemPrice: {
    color: colors.accent,
    fontSize: fontSize.md,
    fontWeight: '700',
  },
  buildModalRemove: {
    padding: 4,
  },
  buildModalFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
  },
  buildModalTotal: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '700',
  },
  buildModalCloseBtn: {
    backgroundColor: colors.aiAssistant,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: spacing.lg,
  },
  buildModalCloseBtnText: {
    color: colors.onAiAssistant,
    fontWeight: '700',
    fontSize: fontSize.md,
  },
  descRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  descAttachBtn: {
    width: 56,
    height: 56,
    borderRadius: 10,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  descAttachThumb: {width: '100%', height: '100%'},
  descInput: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: spacing.md,
    color: colors.text,
    fontSize: fontSize.md,
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 80,
    textAlignVertical: 'top',
    marginBottom: spacing.md,
  },
  descInputFlex: {flex: 1, marginBottom: 0},
  generateBtn: {
    backgroundColor: colors.aiAssistant,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: spacing.xs,
  },
  generateBtnDisabled: {
    opacity: 0.6,
  },
  generateBtnText: {
    color: colors.onAiAssistant,
    fontSize: fontSize.lg,
    fontWeight: '700',
  },
  statusCard: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: spacing.md,
    marginTop: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statusText: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
  },
  imageContainer: {
    marginTop: spacing.md,
    alignItems: 'center',
  },
  imageHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: spacing.sm,
  },
  imageLabel: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '600',
  },
  downloadBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  generatedImage: {
    width: '100%',
    height: 280,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  refineSection: {
    marginTop: spacing.lg,
    backgroundColor: colors.card,
    borderRadius: 12,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  refineTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  refineHistory: {
    marginBottom: spacing.sm,
    gap: 4,
  },
  refineHistoryItem: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
  },
  refineBtn: {
    backgroundColor: colors.primary,
  },

  detailOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  detailPanel: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: 'hidden',
  },
  detailImage: {
    width: '100%',
    height: 220,
    backgroundColor: colors.surfaceLight,
  },
  detailImagePlaceholder: {
    width: '100%',
    height: 220,
    backgroundColor: colors.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailImagePlaceholderText: {
    fontSize: 64,
  },
  detailBody: {
    padding: spacing.md,
  },
  detailSourceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  detailSource: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  detailCondition: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
  },
  detailName: {
    fontSize: fontSize.xl,
    color: colors.text,
    fontWeight: 'bold',
    marginBottom: spacing.sm,
  },
  detailPrice: {
    fontSize: 28,
    color: colors.accent,
    fontWeight: 'bold',
    marginBottom: spacing.md,
  },
  detailAddBtn: {
    backgroundColor: colors.aiAssistant,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  detailAddBtnText: {
    color: colors.onAiAssistant,
    fontSize: fontSize.md,
    fontWeight: '700',
  },
  detailBuyBtn: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  detailBuyBtnText: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '600',
  },
  detailCloseBtn: {
    paddingVertical: 12,
    alignItems: 'center',
  },
  detailCloseBtnText: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
  },

  chatModal: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  chatPanel: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: '85%',
    overflow: 'hidden',
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  chatHeaderTitle: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: 'bold',
  },
  chatCloseBtn: {
    padding: 4,
  },
  chatCloseBtnText: {
    color: colors.textSecondary,
    fontSize: fontSize.xl,
    fontWeight: 'bold',
  },

  chatLocationBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: 4,
  },
  chatLocationLabel: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
  },
  chatLocationChips: {
    flexDirection: 'row',
    gap: 4,
  },
  chatLocationChip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: colors.surfaceLight,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chatLocationChipSelected: {
    backgroundColor: colors.aiAssistant,
    borderColor: colors.aiAssistant,
  },
  chatLocationChipText: {
    fontSize: 10,
    color: colors.textSecondary,
  },
  chatLocationChipTextSelected: {
    color: colors.onAiAssistant,
    fontWeight: '600',
  },

  chatMessageList: {
    padding: spacing.md,
    paddingBottom: spacing.sm,
  },
  chatEmptyState: {
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  chatEmptyIcon: {
    fontSize: 40,
    marginBottom: spacing.sm,
  },
  chatEmptyText: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
    textAlign: 'center',
    paddingHorizontal: spacing.lg,
  },
  chatBubbleWrapper: {
    marginBottom: spacing.sm,
  },
  chatBubble: {
    borderRadius: 12,
    padding: spacing.md,
    maxWidth: '85%',
  },
  chatUserBubble: {
    backgroundColor: colors.aiAssistant,
    alignSelf: 'flex-end',
  },
  chatAiBubble: {
    backgroundColor: colors.surface,
    alignSelf: 'flex-start',
  },
  chatRoleLabel: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    marginBottom: 4,
    fontWeight: '600',
  },
  chatMessageText: {
    color: colors.text,
    fontSize: fontSize.md,
    lineHeight: 20,
  },

  chatPartsSection: {
    alignSelf: 'stretch',
    marginTop: 4,
  },
  chatPartsSectionTitle: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    fontWeight: '600',
    marginBottom: 4,
  },
  chatPartCard: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    overflow: 'hidden',
    marginRight: spacing.sm,
    width: 160,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chatPartImage: {
    width: '100%',
    height: 100,
    backgroundColor: colors.surfaceLight,
  },
  chatPartImagePlaceholder: {
    width: '100%',
    height: 100,
    backgroundColor: colors.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatPartImagePlaceholderText: {
    fontSize: 36,
  },
  chatPartSource: {
    fontSize: 10,
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: spacing.sm,
    marginHorizontal: spacing.sm,
    marginBottom: 4,
  },
  chatPartName: {
    fontSize: fontSize.sm,
    color: colors.text,
    fontWeight: '600',
    marginBottom: 4,
    marginHorizontal: spacing.sm,
    lineHeight: 18,
  },
  chatPartPrice: {
    fontSize: fontSize.md,
    color: colors.accent,
    fontWeight: 'bold',
    marginBottom: 4,
    marginHorizontal: spacing.sm,
  },
  chatPartAddBtn: {
    backgroundColor: colors.aiAssistant,
    paddingVertical: 8,
    alignItems: 'center',
    marginTop: 4,
  },
  chatPartAddBtnText: {
    fontSize: 10,
    color: colors.onAiAssistant,
    fontWeight: '600',
  },

  chatLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
    gap: spacing.sm,
  },
  chatLoadingText: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
  },
  chatInputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    padding: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
    gap: spacing.sm,
  },
  chatInput: {
    flex: 1,
    backgroundColor: colors.surfaceLight,
    borderRadius: 20,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    color: colors.text,
    fontSize: fontSize.md,
    maxHeight: 100,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chatSendBtn: {
    backgroundColor: colors.aiAssistant,
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    justifyContent: 'center',
  },
  chatSendDisabled: {
    opacity: 0.5,
  },
  chatSendText: {
    color: colors.onAiAssistant,
    fontWeight: 'bold',
    fontSize: fontSize.md,
  },
});
