import {StyleSheet} from 'react-native';
import {colors, fontSize, spacing} from '../../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  title: {
    fontSize: fontSize.xxl,
    color: colors.text,
    fontWeight: 'bold',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
  },
  carBanner: {
    backgroundColor: colors.primary,
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    borderRadius: 8,
    padding: spacing.sm,
    alignItems: 'center',
  },
  carBannerText: {
    color: colors.text,
    fontWeight: '600',
    fontSize: fontSize.md,
  },
  tabBar: {
    flexDirection: 'row',
    marginHorizontal: spacing.md,
    marginTop: spacing.md,
    borderRadius: 10,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
  },
  tabActive: {
    backgroundColor: colors.primary,
    borderRadius: 10,
  },
  tabText: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
    fontWeight: '600',
  },
  tabTextActive: {
    color: colors.text,
  },
  content: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  searchRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  searchInput: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 10,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    color: colors.text,
    fontSize: fontSize.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  searchBtn: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    width: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchBtnText: {
    fontSize: fontSize.xl,
  },
  sourceLabel: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    marginTop: spacing.sm,
    marginBottom: 4,
  },
  errorText: {
    color: colors.danger,
    textAlign: 'center',
    marginTop: spacing.md,
  },
  loader: {
    marginTop: spacing.xl,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: spacing.md,
  },
  emptyText: {
    color: colors.textSecondary,
    fontSize: fontSize.lg,
  },
  emptyHint: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    marginTop: spacing.sm,
    textAlign: 'center',
    paddingHorizontal: spacing.xl,
  },
  list: {
    paddingTop: spacing.sm,
    paddingBottom: spacing.lg,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardSelected: {
    borderColor: colors.accent,
    borderWidth: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  partTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '600',
    flex: 1,
  },
  sourceBadge: {
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  sourceBadgeText: {
    color: '#fff',
    fontSize: fontSize.sm,
    fontWeight: '700',
  },
  cardBody: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  price: {
    color: colors.accent,
    fontSize: fontSize.lg,
    fontWeight: 'bold',
  },
  condition: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: 'normal',
  },
  checkmark: {
    color: colors.accent,
    fontSize: fontSize.xxl,
    fontWeight: 'bold',
  },
  linkBtn: {
    marginTop: spacing.sm,
  },
  linkText: {
    color: colors.primaryLight,
    fontSize: fontSize.sm,
  },
  shopAddress: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
    marginTop: 4,
  },
  shopRating: {
    color: colors.warning,
    fontSize: fontSize.md,
    marginTop: 4,
  },
  totalBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
  },
  totalText: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
  },
  totalPrice: {
    color: colors.accent,
    fontSize: fontSize.xl,
    fontWeight: 'bold',
  },
  estimateBtn: {
    backgroundColor: '#7c3aed',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  estimateBtnText: {
    color: '#fff',
    fontSize: fontSize.md,
    fontWeight: '700',
  },
  estimateCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: spacing.md,
    marginTop: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  estimateTitle: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: 'bold',
    marginBottom: spacing.sm,
  },
  estimateRow: {
    marginBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: spacing.sm,
  },
  estimateItemName: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '600',
  },
  estimateItemCost: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    marginTop: 2,
  },
  estimateNote: {
    color: colors.warning,
    fontSize: fontSize.sm,
    fontStyle: 'italic',
    marginTop: 2,
  },
  estimateTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  estimateTotalLabel: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: 'bold',
  },
  estimateTotalValue: {
    color: colors.accent,
    fontSize: fontSize.lg,
    fontWeight: 'bold',
  },
  estimateDisclaimer: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    fontStyle: 'italic',
    marginTop: spacing.sm,
  },
  previewContent: {
    paddingBottom: spacing.xl,
  },
  previewHeading: {
    color: colors.text,
    fontSize: fontSize.xl,
    fontWeight: 'bold',
    marginBottom: spacing.sm,
  },
  previewSubtext: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
    marginBottom: spacing.md,
  },
  previewCart: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: spacing.md,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  previewCartTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  previewCartItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
    gap: spacing.sm,
  },
  previewCartBullet: {
    color: '#7c3aed',
    fontSize: fontSize.lg,
    lineHeight: 18,
  },
  previewCartName: {
    flex: 1,
    color: colors.text,
    fontSize: fontSize.sm,
  },
  previewCartPrice: {
    color: colors.accent,
    fontSize: fontSize.sm,
    fontWeight: '600',
  },
  previewCartHint: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    marginTop: spacing.sm,
    fontStyle: 'italic',
  },
  descInput: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: spacing.md,
    color: colors.text,
    fontSize: fontSize.md,
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 80,
    textAlignVertical: 'top',
    marginBottom: spacing.md,
  },
  generateBtn: {
    backgroundColor: '#7c3aed',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
  },
  generateBtnDisabled: {
    opacity: 0.6,
  },
  generateBtnText: {
    color: '#fff',
    fontSize: fontSize.lg,
    fontWeight: '700',
  },
  statusCard: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: spacing.md,
    marginTop: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statusText: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
  },
  imageContainer: {
    marginTop: spacing.md,
    alignItems: 'center',
  },
  imageLabel: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '600',
    marginBottom: spacing.sm,
  },
  generatedImage: {
    width: '100%',
    height: 280,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  // Part detail modal
  detailOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  detailPanel: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: 'hidden',
  },
  detailImage: {
    width: '100%',
    height: 220,
    backgroundColor: colors.surfaceLight,
  },
  detailImagePlaceholder: {
    width: '100%',
    height: 220,
    backgroundColor: colors.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailImagePlaceholderText: {
    fontSize: 64,
  },
  detailBody: {
    padding: spacing.md,
  },
  detailSourceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  detailSource: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  detailCondition: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
  },
  detailName: {
    fontSize: fontSize.xl,
    color: colors.text,
    fontWeight: 'bold',
    marginBottom: spacing.sm,
  },
  detailPrice: {
    fontSize: 28,
    color: colors.accent,
    fontWeight: 'bold',
    marginBottom: spacing.md,
  },
  detailAddBtn: {
    backgroundColor: '#7c3aed',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  detailAddBtnText: {
    color: '#fff',
    fontSize: fontSize.md,
    fontWeight: '700',
  },
  detailBuyBtn: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  detailBuyBtnText: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '600',
  },
  detailCloseBtn: {
    paddingVertical: 12,
    alignItems: 'center',
  },
  detailCloseBtnText: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
  },
  // Floating AI button
  aiFab: {
    position: 'absolute',
    bottom: 24,
    right: 20,
    backgroundColor: '#7c3aed',
    borderRadius: 28,
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  aiFabText: {
    fontSize: 26,
  },
  // Chat modal
  chatModal: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  chatPanel: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: '85%',
    overflow: 'hidden',
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  chatHeaderTitle: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: 'bold',
  },
  chatCloseBtn: {
    padding: 4,
  },
  chatCloseBtnText: {
    color: colors.textSecondary,
    fontSize: fontSize.xl,
    fontWeight: 'bold',
  },
  // Market selector inside chat
  chatLocationBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: 4,
  },
  chatLocationLabel: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
  },
  chatLocationChips: {
    flexDirection: 'row',
    gap: 4,
  },
  chatLocationChip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: colors.surfaceLight,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chatLocationChipSelected: {
    backgroundColor: '#7c3aed',
    borderColor: '#7c3aed',
  },
  chatLocationChipText: {
    fontSize: 10,
    color: colors.textSecondary,
  },
  chatLocationChipTextSelected: {
    color: '#fff',
    fontWeight: '600',
  },
  // Chat messages
  chatMessageList: {
    padding: spacing.md,
    paddingBottom: spacing.sm,
  },
  chatEmptyState: {
    alignItems: 'center',
    paddingVertical: spacing.xl,
  },
  chatEmptyIcon: {
    fontSize: 40,
    marginBottom: spacing.sm,
  },
  chatEmptyText: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
    textAlign: 'center',
    paddingHorizontal: spacing.lg,
  },
  chatBubbleWrapper: {
    marginBottom: spacing.sm,
  },
  chatBubble: {
    borderRadius: 12,
    padding: spacing.md,
    maxWidth: '85%',
  },
  chatUserBubble: {
    backgroundColor: '#7c3aed',
    alignSelf: 'flex-end',
  },
  chatAiBubble: {
    backgroundColor: colors.surface,
    alignSelf: 'flex-start',
  },
  chatRoleLabel: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    marginBottom: 4,
    fontWeight: '600',
  },
  chatMessageText: {
    color: colors.text,
    fontSize: fontSize.md,
    lineHeight: 20,
  },
  // AI-suggested parts in chat
  chatPartsSection: {
    alignSelf: 'stretch',
    marginTop: 4,
  },
  chatPartsSectionTitle: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    fontWeight: '600',
    marginBottom: 4,
  },
  chatPartCard: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    overflow: 'hidden',
    marginRight: spacing.sm,
    width: 160,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chatPartImage: {
    width: '100%',
    height: 100,
    backgroundColor: colors.surfaceLight,
  },
  chatPartImagePlaceholder: {
    width: '100%',
    height: 100,
    backgroundColor: colors.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatPartImagePlaceholderText: {
    fontSize: 36,
  },
  chatPartSource: {
    fontSize: 10,
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: spacing.sm,
    marginHorizontal: spacing.sm,
    marginBottom: 4,
  },
  chatPartName: {
    fontSize: fontSize.sm,
    color: colors.text,
    fontWeight: '600',
    marginBottom: 4,
    marginHorizontal: spacing.sm,
    lineHeight: 18,
  },
  chatPartPrice: {
    fontSize: fontSize.md,
    color: colors.accent,
    fontWeight: 'bold',
    marginBottom: 4,
    marginHorizontal: spacing.sm,
  },
  chatPartAddBtn: {
    backgroundColor: '#7c3aed',
    paddingVertical: 8,
    alignItems: 'center',
    marginTop: 4,
  },
  chatPartAddBtnText: {
    fontSize: 10,
    color: '#fff',
    fontWeight: '600',
  },
  // Chat loading + input
  chatLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
    gap: spacing.sm,
  },
  chatLoadingText: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
  },
  chatInputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    padding: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
    gap: spacing.sm,
  },
  chatInput: {
    flex: 1,
    backgroundColor: colors.surfaceLight,
    borderRadius: 20,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    color: colors.text,
    fontSize: fontSize.md,
    maxHeight: 100,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chatSendBtn: {
    backgroundColor: '#7c3aed',
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    justifyContent: 'center',
  },
  chatSendDisabled: {
    opacity: 0.5,
  },
  chatSendText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: fontSize.md,
  },
});
