import {StyleSheet} from 'react-native';
import type {ColorPalette} from '../../theme/colors';
import {createShadows, fontSize, radius, spacing} from '../../theme';

export const createDIYScreenStyles = (colors: ColorPalette) => {
  const shadows = createShadows(colors);
  return StyleSheet.create({
  container: {flex: 1, backgroundColor: colors.background},
  flex: {flex: 1},
  scroll: {padding: spacing.lg, paddingBottom: spacing.xxl},
  carBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.card,
    padding: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  carBannerText: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '600',
    flex: 1,
  },
  sectionLabel: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    fontWeight: '600',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: spacing.xs,
  },
  heading: {
    fontSize: fontSize.xxl,
    color: colors.text,
    fontWeight: '700',
    marginBottom: spacing.md,
    letterSpacing: -0.3,
  },
  problemCard: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.md,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.soft,
  },
  textArea: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    padding: spacing.md,
    color: colors.text,
    fontSize: fontSize.lg,
    minHeight: 120,
    borderWidth: 1,
    borderColor: colors.border,
    lineHeight: 22,
  },
  diagnoseButton: {marginBottom: spacing.lg},
  disabled: {opacity: 0.5},
  quickSection: {marginBottom: spacing.lg},
  quickTitle: {
    fontSize: fontSize.md,
    color: colors.textSecondary,
    marginBottom: spacing.md,
    fontWeight: '500',
  },
  quickGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm},
  quickChip: {
    width: '48%',
    flexGrow: 1,
    minWidth: '46%',
    minHeight: 96,
    backgroundColor: colors.card,
    borderRadius: radius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.soft,
  },
  quickChipInner: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  quickChipText: {
    color: colors.text,
    fontSize: fontSize.sm,
    fontWeight: '600',
    textAlign: 'center',
  },
  loadingContainer: {alignItems: 'center', paddingVertical: spacing.xl},
  loadingText: {
    color: colors.textSecondary,
    marginTop: spacing.md,
    fontSize: fontSize.md,
  },
  results: {gap: spacing.md},
  workshopWarning: {
    backgroundColor: 'rgba(255, 69, 58, 0.12)',
    borderRadius: radius.lg,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: 'rgba(255, 69, 58, 0.35)',
  },
  workshopText: {
    color: colors.danger,
    fontSize: fontSize.md,
    flex: 1,
    lineHeight: 20,
    fontWeight: '600',
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.soft,
  },
  warningCard: {
    borderColor: 'rgba(255, 69, 58, 0.3)',
    backgroundColor: 'rgba(255, 69, 58, 0.08)',
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  cardTitle: {
    fontSize: fontSize.lg,
    color: colors.text,
    fontWeight: '700',
  },
  cardContent: {
    fontSize: fontSize.md,
    color: colors.textSecondary,
    lineHeight: 22,
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radius.pill,
  },
  badgeText: {
    color: colors.onPrimary,
    fontSize: fontSize.xs,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  metaText: {color: colors.textMuted, fontSize: fontSize.sm},
  warningItem: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
    marginBottom: 6,
    lineHeight: 20,
  },
  toolsGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm},
  toolChip: {
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
  },
  toolChipText: {color: colors.text, fontSize: fontSize.sm},
  stepRow: {
    flexDirection: 'row',
    marginBottom: spacing.md,
    gap: spacing.md,
  },
  stepNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepNumberText: {
    color: colors.onPrimary,
    fontWeight: '700',
    fontSize: fontSize.sm,
  },
  stepText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: fontSize.md,
    lineHeight: 22,
  },
  costBlock: {
    marginBottom: spacing.md,
    paddingBottom: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  costLabel: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '600',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  costValue: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '600',
    lineHeight: 22,
    flexWrap: 'wrap',
  },
  followUpCard: {
    backgroundColor: colors.cardElevated,
    borderRadius: radius.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 10, 0.2)',
  },
  followUpTitle: {
    fontSize: fontSize.lg,
    color: colors.text,
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  followUpQuestion: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
    marginBottom: 6,
    lineHeight: 20,
  },
  followUpInput: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    padding: spacing.md,
    color: colors.text,
    fontSize: fontSize.md,
    minHeight: 80,
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: spacing.sm,
    marginBottom: spacing.md,
  },
  newButton: {marginTop: spacing.sm},
  });
};
