import {StyleSheet} from 'react-native';
import {colors, fontSize, spacing} from '../../theme';

export default StyleSheet.create({
  container: {flex: 1, backgroundColor: colors.background},
  flex: {flex: 1},
  scroll: {padding: spacing.lg},
  carBanner: {
    backgroundColor: colors.surface,
    padding: spacing.sm,
    borderRadius: 8,
    marginBottom: spacing.md,
  },
  carBannerText: {
    color: colors.primary,
    fontSize: fontSize.sm,
    fontWeight: '600',
    textAlign: 'center',
  },
  heading: {
    fontSize: fontSize.xl,
    color: colors.text,
    fontWeight: 'bold',
    marginBottom: spacing.md,
  },
  textArea: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: spacing.md,
    color: colors.text,
    fontSize: fontSize.md,
    minHeight: 100,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.md,
  },
  diagnoseButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  disabled: {opacity: 0.5},
  diagnoseButtonText: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: 'bold',
  },
  quickSection: {marginBottom: spacing.lg},
  quickTitle: {
    fontSize: fontSize.md,
    color: colors.textSecondary,
    marginBottom: spacing.sm,
  },
  quickGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm},
  quickButton: {
    backgroundColor: colors.surface,
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  quickButtonText: {color: colors.text, fontSize: fontSize.md},
  loadingContainer: {alignItems: 'center', paddingVertical: spacing.xl},
  loadingText: {
    color: colors.textSecondary,
    marginTop: spacing.md,
    fontSize: fontSize.md,
  },
  results: {gap: spacing.md},
  workshopWarning: {
    backgroundColor: '#7f1d1d',
    borderRadius: 12,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  workshopIcon: {fontSize: 24},
  workshopText: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '600',
    flex: 1,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: spacing.md,
  },
  warningCard: {borderWidth: 1, borderColor: colors.warning},
  cardTitle: {
    fontSize: fontSize.lg,
    color: colors.text,
    fontWeight: 'bold',
    marginBottom: spacing.sm,
  },
  cardContent: {
    color: colors.text,
    fontSize: fontSize.md,
    lineHeight: 22,
    marginBottom: spacing.sm,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  badge: {paddingVertical: 4, paddingHorizontal: 10, borderRadius: 12},
  badgeText: {
    color: colors.text,
    fontSize: fontSize.sm,
    fontWeight: 'bold',
    textTransform: 'capitalize',
  },
  metaText: {color: colors.textSecondary, fontSize: fontSize.sm},
  warningItem: {
    color: colors.warning,
    fontSize: fontSize.md,
    marginBottom: spacing.xs,
  },
  toolsGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm},
  toolChip: {
    backgroundColor: colors.surfaceLight,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
  },
  toolChipText: {color: colors.text, fontSize: fontSize.sm},
  stepRow: {flexDirection: 'row', marginBottom: spacing.sm, gap: spacing.sm},
  stepNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepNumberText: {color: colors.text, fontWeight: 'bold', fontSize: fontSize.sm},
  stepText: {color: colors.text, fontSize: fontSize.md, lineHeight: 22, flex: 1},
  costRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
  },
  costLabel: {color: colors.textSecondary, fontSize: fontSize.md},
  costValue: {color: colors.accent, fontSize: fontSize.md, fontWeight: 'bold'},
  followUpCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.primary,
    gap: spacing.sm,
  },
  followUpTitle: {
    fontSize: fontSize.lg,
    color: colors.text,
    fontWeight: 'bold',
  },
  followUpQuestion: {
    color: colors.textSecondary,
    fontSize: fontSize.md,
    lineHeight: 22,
  },
  followUpInput: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 8,
    padding: spacing.md,
    color: colors.text,
    fontSize: fontSize.md,
    minHeight: 80,
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: spacing.xs,
  },
  followUpButton: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  followUpButtonText: {
    color: colors.text,
    fontWeight: 'bold',
    fontSize: fontSize.md,
  },
  newButton: {
    backgroundColor: colors.surfaceLight,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  newButtonText: {color: colors.text, fontSize: fontSize.lg, fontWeight: 'bold'},
});
