import {StyleSheet} from 'react-native';
import type {ColorPalette} from '../../theme/colors';
import {createShadows, fontSize, radius, spacing} from '../../theme';

export const createHomeScreenStyles = (colors: ColorPalette) => {
  const shadows = createShadows(colors);
  return StyleSheet.create({
  container: {flex: 1, backgroundColor: colors.background},
  flex: {flex: 1},
  scroll: {paddingHorizontal: spacing.lg, paddingBottom: spacing.xxl},
  header: {
    paddingTop: spacing.sm,
    marginBottom: spacing.lg,
  },
  greeting: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    fontWeight: '600',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  title: {
    fontSize: fontSize.hero,
    color: colors.text,
    fontWeight: '700',
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: fontSize.md,
    color: colors.textSecondary,
    marginTop: 6,
  },
  heroCard: {
    marginBottom: spacing.lg,
    borderRadius: radius.xl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.cardElevated,
    ...shadows.card,
  },
  heroImage: {
    width: '100%',
    height: 200,
  },
  heroImagePlaceholder: {
    width: '100%',
    height: 200,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroImageEditBtn: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(0,0,0,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroOverlay: {
    padding: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  heroLabel: {
    fontSize: fontSize.xs,
    color: colors.primary,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  heroCarName: {
    fontSize: fontSize.xxl,
    color: colors.text,
    fontWeight: '700',
    marginBottom: spacing.md,
  },
  statsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  statPill: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    paddingVertical: 10,
    paddingHorizontal: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  statValue: {
    fontSize: fontSize.lg,
    color: colors.text,
    fontWeight: '700',
  },
  statLabel: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    marginTop: 2,
  },
  emptyHero: {
    padding: spacing.xl,
    alignItems: 'center',
  },
  emptyHeroIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.primaryMuted,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  emptyHeroTitle: {
    fontSize: fontSize.xl,
    color: colors.text,
    fontWeight: '700',
    marginBottom: spacing.xs,
  },
  emptyHeroText: {
    fontSize: fontSize.md,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: spacing.lg,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontSize: fontSize.xl,
    color: colors.text,
    fontWeight: '700',
  },
  quickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  quickCard: {
    width: '48%',
    flexGrow: 1,
    minWidth: '46%',
    minHeight: 120,
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.soft,
  },
  quickIconWrap: {
    width: 40,
    height: 40,
    borderRadius: radius.sm,
    backgroundColor: colors.primaryMuted,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  quickTitle: {
    fontSize: fontSize.md,
    color: colors.text,
    fontWeight: '700',
    marginBottom: 2,
    textAlign: 'center',
  },
  quickSubtitle: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    lineHeight: 16,
    textAlign: 'center',
  },
  form: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.card,
  },
  formTitle: {
    fontSize: fontSize.xl,
    color: colors.text,
    fontWeight: '700',
    marginBottom: spacing.md,
  },
  input: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    padding: spacing.md,
    color: colors.text,
    fontSize: fontSize.lg,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  photoButton: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    height: 110,
    marginBottom: spacing.sm,
    overflow: 'hidden',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  photoButtonText: {color: colors.textSecondary, fontSize: fontSize.md},
  photoPreview: {width: '100%', height: '100%'},
  formButtons: {flexDirection: 'row', gap: spacing.sm, marginTop: spacing.sm},
  carsSection: {marginBottom: spacing.lg},
  garageHint: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    marginBottom: spacing.sm,
  },
  garageList: {
    gap: spacing.sm,
    paddingRight: spacing.lg,
  },
  garageCard: {
    width: 148,
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.sm,
    marginRight: spacing.sm,
    ...shadows.soft,
  },
  garageCardSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.cardElevated,
  },
  garageThumbWrap: {
    position: 'relative',
    width: '100%',
    marginBottom: spacing.sm,
  },
  garageThumb: {
    width: '100%',
    height: 88,
    borderRadius: radius.md,
  },
  garageDeleteBtn: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  garageCarName: {
    fontSize: fontSize.md,
    fontWeight: '700',
    color: colors.text,
  },
  garageCarModel: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    marginTop: 2,
    marginBottom: spacing.xs,
  },
  resetLink: {
    color: colors.danger,
    fontSize: fontSize.sm,
    fontWeight: '600',
  },
  carCard: {
    backgroundColor: colors.card,
    borderRadius: radius.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    minHeight: 76,
    ...shadows.soft,
  },
  carCardRow: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
  },
  carCardSelected: {
    borderColor: 'rgba(255, 214, 10, 0.45)',
    backgroundColor: colors.cardElevated,
  },
  cardThumb: {width: 76, height: 76},
  cardInfo: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.md,
  },
  carName: {fontSize: fontSize.lg, color: colors.text, fontWeight: '600'},
  activeBadge: {
    backgroundColor: colors.primaryMuted,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radius.pill,
  },
  activeLabel: {
    fontSize: fontSize.xs,
    color: colors.primary,
    fontWeight: '700',
  },
  });
};
