import {StyleSheet} from 'react-native';
import {colors, fontSize, spacing} from '../../theme';

export default StyleSheet.create({
  container: {flex: 1, backgroundColor: colors.background},
  flex: {flex: 1},
  scroll: {padding: spacing.lg, alignItems: 'center'},
  title: {fontSize: fontSize.title, color: colors.text, fontWeight: 'bold', marginTop: spacing.lg},
  subtitle: {fontSize: fontSize.lg, color: colors.textSecondary, marginTop: spacing.xs, marginBottom: spacing.lg},
  selectedCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: spacing.md,
    width: '100%',
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.primary,
    overflow: 'hidden',
  },
  selectedImage: {width: '100%', height: 160, borderRadius: 8, marginBottom: spacing.sm},
  selectedLabel: {fontSize: fontSize.sm, color: colors.primary, fontWeight: '600', marginBottom: spacing.xs},
  selectedCar: {fontSize: fontSize.xl, color: colors.text, fontWeight: 'bold'},
  addButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    paddingHorizontal: spacing.xl,
    borderRadius: 10,
    width: '100%',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  addButtonText: {color: colors.text, fontSize: fontSize.lg, fontWeight: 'bold'},
  form: {backgroundColor: colors.surface, borderRadius: 12, padding: spacing.lg, width: '100%', marginBottom: spacing.md},
  formTitle: {fontSize: fontSize.xl, color: colors.text, fontWeight: 'bold', marginBottom: spacing.md},
  input: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 8,
    padding: spacing.md,
    color: colors.text,
    fontSize: fontSize.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  photoButton: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    height: 100,
    marginBottom: spacing.sm,
    overflow: 'hidden',
  },
  photoButtonText: {color: colors.textSecondary, fontSize: fontSize.md},
  photoPreview: {width: '100%', height: '100%'},
  formButtons: {flexDirection: 'row', gap: spacing.sm, marginTop: spacing.sm},
  saveButton: {flex: 1, backgroundColor: colors.accent, paddingVertical: 12, borderRadius: 8, alignItems: 'center'},
  saveButtonText: {color: colors.text, fontWeight: 'bold', fontSize: fontSize.md},
  cancelButton: {flex: 1, backgroundColor: colors.surfaceLight, paddingVertical: 12, borderRadius: 8, alignItems: 'center'},
  cancelButtonText: {color: colors.textSecondary, fontWeight: 'bold', fontSize: fontSize.md},
  carsSection: {width: '100%', marginTop: spacing.sm},
  sectionTitle: {fontSize: fontSize.xl, color: colors.text, fontWeight: 'bold', marginBottom: spacing.sm},
  carCard: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    marginBottom: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  carCardSelected: {borderColor: colors.primary},
  cardThumb: {width: 72, height: 72},
  cardInfo: {flex: 1, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: spacing.md},
  carName: {fontSize: fontSize.lg, color: colors.text, fontWeight: '600'},
  activeLabel: {fontSize: fontSize.sm, color: colors.primary, fontWeight: 'bold'},
});
